#trade-system-eureka-server 模块配置文件

#应用名称
spring:
    application:
        name: spring-cloud-eureka
#端口
server:
    port: 8103

#安全认证配置
security:
    basic:
        enabled: true
    user:
        name: admin
        password: admin123

eureka:
    instance:
        hostname: server3
    client:
        register-with-eureka: true
        fetch-registry: true
        serviceUrl:
            defaultZone: http://${security.user.name}:${security.user.password}@server1:8101/eureka/,http://${security.user.name}:${security.user.password}@server2:8102/eureka/
    server:
        enable-self-preservation: false
